language: python
services:
  - postgresql
install:
  - pip install .
  - pip install -r test-requirements.txt
script:
  - POSTGRES_HOST=localhost MODE=direct pytest
  - POSTGRES_HOST=localhost MODE=patch pytest
  - psql -c "alter role postgres with password 'tiger'" -U postgres
  - POSTGRES_HOST=localhost MODE=direct POSTGRES_PASSWORD=tiger pytest
  - POSTGRES_HOST=localhost MODE=patch POSTGRES_PASSWORD=tiger pytest

